version: "3.7"
services:
  validator-import-launchpad:
    container_name: validator-import-launchpad-2
    image: gcr.io/prysmaticlabs/prysm/validator:${PRYSM_VERSION}
    command: accounts import --keys-dir="/launchpad/validator_keys_2" --wallet-dir="/data/wallets" --wallet-password-file="/launchpad/wallet-password" --accept-terms-of-use --${ETH_NETWORK}
    volumes:
      - ./launchpad:/launchpad
      - ${DOCKER_VOL_PATH}/validator-2:/data
  validator-list-accounts:
    container_name: validator_list_accounts-2
    image: gcr.io/prysmaticlabs/prysm/validator:${PRYSM_VERSION}
    command: accounts list --wallet-dir="/data/wallets" --wallet-password-file="/launchpad/wallet-password" --accept-terms-of-use --${ETH_NETWORK}
    volumes:
      - ./launchpad:/launchpad
      - ${DOCKER_VOL_PATH}/validator-2:/data